name: Deploy React Frontend Using Cloudformation and S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: T6xyz-Service-Frontend
        run: npm ci

      - name: Build React app
        working-directory: T6xyz-Service-Frontend
        run: npm run build
