name: Deploy React Frontend Using Cloudformation and S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1 
      REACT_DIR: ./T6xyz-Service-Frontend
      CDK_DIR: ./T6xyz-Service-CDK

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install CDK dependencies
        working-directory: ${{ env.CDK_DIR }}
        run: npm ci

      - name: Install React dependencies
        working-directory: ${{ env.REACT_DIR }}
        run: npm ci

      - name: Build React App
        working-directory: ${{ env.REACT_DIR }}
        run: npm run build

      - name: Synth CDK
        working-directory: ${{ env.CDK_DIR }}
        run: npx cdk synth 

      - name: 🚀 Deploy CDK
        working-directory: ${{ env.CDK_DIR }}
        run: npx cdk deploy --all --require-approval never 

